var aw1 = "rawalpindi";
var bw2 = "islamabaad";
console.log(aw1 == bw2);
console.log(aw1 != bw2);
console.log("\n\n");
console.log(aw1 == 'Rawalpindi');
console.log(aw1 != 'Rawalpindi');
console.log("\n\n");
console.log(1 > 2);
console.log(1 < 2);
console.log(1 == 1);
console.log(2 != 2);
console.log(3 >= 3);
console.log(2 >= 323);
console.log(19 <= 20);
console.log(191 <= 20);
console.log("\n\n");
console.log(aw1 != bw2 && 2 > 1);
console.log(aw1 == bw2 && 2 <= 1);
console.log("\n\n");
console.log('Rawalpindi' != aw1 || 1 >= 1);
console.log('Rawalpindi' == aw1 || 0 >= 1);
console.log("\n\n");
var i11 = [1, 2, 4];
console.log(i11[2] == 4);
console.log(i11[1] == 34);
